name: Test BackTool CLI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run tests
      run: npm test
    
    - name: Test MongoDB setup
      run: npx backtool --project test-mongo --database MongoDB
    
    - name: Test PostgreSQL setup
      run: npx backtool --project test-postgres --database PostgreSQL
    
    - name: Test MySQL setup
      run: npx backtool --project test-mysql --database MySQL
    
    - name: Test SQLite setup
      run: npx backtool --project test-sqlite --database SQLite